### ISSUE TITLE
fix: Update pdffit2 build CI that does Windows Py311 312 wheel build by Tieqiong

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#123]
See the new changed in https://github.com/diffpy/diffpy.pdffit2/pull/111

**Comment by bobleesj** [comment]
```yaml
build_wheels:

    defaults:
        run:
          shell: bash -l {0}

    name: Build wheel ${{ matrix.python[0] }}-${{ matrix.buildplat[0] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-latest, manylinux_x86_64]
          - [macos-13, macosx_x86_64]
          - [macos-14, macosx_arm64]
          - [windows-latest, win_amd64]
        python:
          - ["3.11", "cp311"]
          - ["3.12", "cp312"]

    steps:
      - name: Check out #${{ inputs.project }}
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python[0] }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python[0] }}

      - name: Build wheels for Linux
        if: runner.os == 'Linux'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          CIBW_BEFORE_BUILD: yum install -y gsl-devel && pip install -e .
        with:
          output-dir: wheelhouse

      - name: Build wheels for macOS
        if: runner.os == 'macOS'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          MACOSX_DEPLOYMENT_TARGET: 13.0
          CIBW_BEFORE_BUILD: brew install gsl && pip install -e .
        with:
          output-dir: wheelhouse

      - name: Set up conda for Windows
        if: runner.os == 'Windows'
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: gsl
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: install gsl for Windows
        if: runner.os == 'Windows'
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install gsl
      - name: Build wheels for Windows
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          CONDA_PREFIX: ${{ env.CONDA_PREFIX }}
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[0] }}
          path: ./wheelhouse/*.whl
```
