### ISSUE TITLE
Remove Python v3.12 setup in `_tests-on-pr.yml` and `_publish-docs-on-release.yml`

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#74]
As many dependencies do not support Python 3.13, we are explicitly setting `python-version: 3.12` in our centralized workflows mentioned in the title:

```
        with:
          activate-environment: build
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.12
```
